version: "3"

services:

  http-balancer:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/app/static:/var/www/static:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend

  backend:
    build: public/app
    restart: always
    command: python -Wd manage.py runserver 0.0.0.0:8000
    depends_on:
      - cache
      - mailhog

  cache:
    restart: always
    image: redis:latest

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"