# Generated by Django 5.0.3 on 2024-04-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
